spring:
    datasource:
        name: data
        url: jdbc:mysql://127.0.0.1:3306/pinshang?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        maxActive: 20
        initialSize: 5
        maxWait: 30000
        minIdle: 5
        maxIdle: 10
        removeAbandonedTimeout: 120
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        validationQuery: select 1

zuul:
  routes:
    CLOUD-SERVICE: /api/**
